AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

Style/ConditionalAssignment:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/RedundantReturn:
  Enabled: true
Style/Documentation:
  Enabled: true
Style/WordArray:
  Enabled: true
Metrics/AbcSize:
  Enabled: true
Style/MutableConstant:
  Enabled: true
Style/SignalException:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Style/MissingRespondToMissing:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
Layout/LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: true
Bundler/OrderedGems:
  Enabled: true
