meta_product_name: 'Local Response'
meta_title: 'Local Response - Brining Commuities together'
meta_description: 'Help those that need it most in times of risis and hardship and bring your community closer together.'
meta_image: 'cover.png' # should exist in `app/assets/images/`
